//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Drawing;
namespace Украшения
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
        public string OldCost
        {
            get
            {
                if (ProductDiscountAmount > 0)
                    return Math.Round(ProductCost, 2).ToString();
                else
                {
                    return "";
                }
            }
        }

        public decimal NewCost
        {
            get
            {
                if (ProductDiscountAmount > 0)
                {
                    return Math.Round((decimal)ProductCost - (decimal)ProductCost * (decimal)ProductDiscountAmount / 100, 2);
                }
                else
                {
                    return Math.Round((decimal)ProductCost, 2);
                }
            }
        }

        public SolidColorBrush FonStyle
        {
            get
            {
                if (ProductDiscountAmount >= 20)
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("LightGreen");

                }
                else
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("White");
                }
            }
        }


        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCategory { get; set; }
        public string ProductManufacturer { get; set; }
        public decimal ProductCost { get; set; }
        public int ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductPostav { get; set; }
        public string ProductUnit { get; set; }
        public string ProductPhoto { get; set; }
        public int ProductMaxDiscount { get; set; }
        
  
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
